### ISSUE TITLE
Datalib dependecy incorrect

### ISSUE THREAD

**Issue by JGameCreation** [klasleino/fast-geometric-projections#1]
Hi! Firstly, thanks for the great paper! Unfortunately I have issues installing fgp-cert. You seems to use datalib as a library of data sets:
`from datalib import Mnist
from datalib import Cifar10
from datalib import FashionMnist`
However, when I install fgp-cert using pip it installs some random time series library as datalib. It would be great if you could fix that!
Best, Jannis

**Comment by klasleino** [comment]
This is fixed now; the correct dependency was datalib-dev
